export class Detailed {
  direction: string;     // 方向
  classify: string;      // 分类
  img: string; // 课程图片
  name: string;          // 课程名称
  difficulty: string;    // 课程难度
  time: string;          // 课程时长
  people: string;        // 学习人数
  know: string;          // 课程须知
  learnWhat: string;     // 学到什么
  authorImg: string;     // 老师头像
  authorName: string;    // 老师姓名
  authorJob: string;     // 老师职业
  learned: number;       // 学生学习百分比
  learnTime: string;     // 学生学习耗时
  learnProgress: string; // 学生学习进度
  sectionId: number; // 开始学习的节
  signature: string; // 签名
  intro: string; // 课程简介
}
